# Generated by Django 4.1 on 2022-08-22 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=30)),
                ('mensaje', models.CharField(max_length=500)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
