# Generated by Django 4.1 on 2022-09-08 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citas',
            options={'ordering': ['creado_en']},
        ),
    ]
