# Generated by Django 4.1 on 2022-09-09 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_alter_citas_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citas',
            options={'ordering': ['-creado_en']},
        ),
    ]
